function createaxes(Parent1, X1, YMatrix1)
%CREATEAXES(PARENT1, X1, YMATRIX1)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 04-Apr-2016 17:55:18

% Create axes
axes1 = axes('Parent',Parent1,'LineWidth',1.5,'FontSize',15);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Marker','+','LineStyle','none');

